# dvc.yaml
stages:
  get_data:
    cmd: python scripts/data.py
    deps:
      - scripts/data.py
    params:
      - index_col
      - cols_to_drop
    outs:
      - data/initial_data.csv
  fit_model:
    cmd: python scripts/fit.py
    deps:
      - data/initial_data.csv
      - scripts/fit.py
    params:
      - target_col
      - binary_drop
      - cat_drop
    outs:
      - models/fitted_model.pkl
  evaluate_model:
    cmd: python scripts/evaluate.py
    deps:
      - models/fitted_model.pkl
      - scripts/evaluate.py
    params:
      - target_col
      - n_splits
      - n_jobs
      - metrics
      - shuffle
      - random_state
    outs:
      - cv_results/cv_res.json